### ISSUE TITLE
Could not import MapnikTileSource

### ISSUE THREAD

**Issue by Acmenwangtuo** [CancerDataScience/HistomicsML-TA#47]
When I click review,i can't see the result 
![Screenshot from 2020-02-04 14-41-34](https://user-images.githubusercontent.com/25858179/73720357-b6f08200-475c-11ea-9e07-6cc44964d029.png)

**Comment by Acmenwangtuo** [comment]
![Screenshot from 2020-02-04 14-49-36](https://user-images.githubusercontent.com/25858179/73720738-9aa11500-475d-11ea-9140-8412e838871c.png)

**Comment by slee172** [comment]
I think one of the reasons of the error is that your ip address of the server container is not properly set up. After starting the Apache server "service apache2 start", you need to set up the ip address here "/var/www/html/HistomicsML/php/hostspecs.php". Confirm it using "cat /var/www/html/HistomicsML/php/hostspecs.php", then you can see "$IIPServer = "http://localhost/fcgi-bin/iipsrv.fcgi?";".
The IIPServer setting should be "localhost" like above if you don't use static IP address on your own machine (i.e. laptop). However, the IIPServer setting should be your IP address (i.e. xxx.xxx.xxx.xxx) if your machine has been assigned static IP address  (This typically happens when you are using a server).
**Another reason I would guess is that your database container is not properly connected to the server container. Try to find the docker container for the database. See the subsection "Runing the HistomicsML database container" from https://histomicsml-taf.readthedocs.io/en/latest/example-data.html**
If you still see the error, showing your full log message would be helpful.

**Comment by cooperlab** [comment]
Fixed by pull request #48

**Comment by Acmenwangtuo** [comment]
It still don't work
INFO:root:Created LRU Cache for 'tilesource' with 2686 maximum size
INFO:root:Notice: Could not import MapnikTileSource
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0303 07:05:39.299856 140228533643072 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0303 07:05:39.314635 140228533643072 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0303 07:05:39.316373 140228533643072 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0303 07:05:39.338979 140228533643072 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0303 07:05:40.866888 140228533643072 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0303 07:05:40.867279 140228533643072 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

**Comment by Acmenwangtuo** [comment]
![image](https://user-images.githubusercontent.com/25858179/75751678-03ca7700-5d62-11ea-8c9b-b07dc5e3b1f7.png)

**Comment by slee172** [comment]
@Acmenwangtuo I think this issue should be closed. You are supposed to do just re-loaded one of pre-trained sample classifiers rather than creating use one. This means that the whole-slide information should not be displayed in the Review because you ran the example docker that doesn't have all whole-slides (I think). If you get a change to confirm that the Review tab works, you probably need to create a new classifier and then go and confirm the Review after choosing new samples.
